"""
Pydantic models describing the SQL Generator output.

The LLM NEVER returns raw text.

It must always return JSON matching these models.
"""

from typing import Any

from pydantic import BaseModel, Field


class SQLAction(BaseModel):
    """
    One SQL statement generated by the LLM.
    """

    reasoning: str = Field(
        description="Why this SQL answers the user's request."
    )

    sql: str = Field(
        description="Parameterized PostgreSQL SQL."
    )

    parameters: list[Any] = Field(
        default_factory=list,
        description="Values for $1, $2 ... placeholders."
    )


class SQLGenerationResult(BaseModel):
    """
    Wrapper returned by the SQL Generator.

    If success=False, the router can respond
    without touching the database.
    """

    success: bool

    action: SQLAction | None = None

    error: str | None = None